Make default credential optional
Azure/azure-service-operator pull request #2758
Opened 2023-03-01 12:02 UTC by super-harsh

Closes #2725 

**Special notes for your reviewer**:

I did consider and tried to have envtest for this, however, changes are in `main` or `ARMClientCache` for which envtest makes no sense as we create test environment distinct from `main` so any test would not test any changes in main and will have to replicate changes in envtest environment. We can have an e2e suite test(not sure if we still want to have it) for this by using a task to create operator without `subscriptionID` and run the suite test on it(like how we do for `multi-tenant` and `pre-release` tests. 

For now, I have included an `ARMClientCache` unit test.

**If applicable**:
- [x] this PR contains tests

2023-03-02 02:15 UTC, theunrepentantgeek commented on v2/cmd/controller/main.go
> +		setupLog.Info("No default credential set found, continuing without default credential")
Are we calling this a _global_ credential or a _default_ one? 

Our users will be reading both the documentation and the logs - we should be consistent, else we run the risk of being confusing.

Remember also that some associate `default` with failure - when you _default_ on a loan, you've failed to pay it back.

Also, is this one credential, or many? A "credential set" implies one or more different credentials, but that doesn't match the code.

Maybe this?

```suggestion
		setupLog.Info("No global credential configured, continuing without.")
```

2023-03-02 02:17 UTC, theunrepentantgeek commented on v2/internal/reconcilers/arm/arm_client_cache.go
> +		return nil, "", errors.New("Default global credential is not configured. Use either namespaced or per-resource credential")
```suggestion
		return nil, "", errors.New("Global credential not configured, you must use either namespaced or per-resource credentials")
```

2023-03-02 02:18 UTC, theunrepentantgeek approved these changes
Pleasantly surprised by how brief this change is. Some minor changes to wording required, but otherwise looks good. :shipit:

2023-03-02 21:12 UTC, matthchr requested changes
I think you also need to update azure-service-operator/v2/config/manager/manager_image_patch.yaml to make the `SUBSCRIPTION_ID` optional.

Same for `AZURE_TENANT_ID` and `AZURE_CLIENT_ID` which also aren't marked optional right now.

2023-03-02 21:12 UTC, matthchr commented on docs/hugo/content/introduction/authentication.md
> +To use Service Principal authentication, specify an `aso-controller-settings` secret with the `AZURE_CLIENT_ID` and `AZURE_CLIENT_SECRET` keys set. This Service Principal is used as a default global
Consider rephrasing the second sentence here to: "This Service Principal is used as a default global credential and is optional. If you do not specify a global credential, you must follow the instructions in [single-operator-multitenancy](https://azure.github.io/azure-service-operator/introduction/multitenant-deployment/#single-operator-multitenancy-default) to specify per-namespace or per-resource credentials"

2023-03-02 21:12 UTC, matthchr commented on v2/cmd/controller/main.go
> +			os.Exit(1)
IMO do `errors.Wrapf` here, drop the `os.Exit(1)` and return the error. Then where this is called, do:
```
if err != nil { 
    log the error
    os.Exit(1)
}
```

Currently where this method is called you don't do anything with the error, which I think should trip our linters too...

2023-03-02 21:12 UTC, matthchr commented on v2/cmd/controller/main.go
> +	credential, err := getGetDefaultCredential(cfg, setupLog)
Need to check `err` here?

2023-03-02 21:12 UTC, matthchr commented on v2/internal/reconcilers/arm/arm_client_cache.go
> +		return nil, "", errors.New("Global credential not configured, you must use either namespaced or per-resource credentials")
nice

2023-03-13 19:59 UTC, matthchr approved these changes

2023-03-13 22:39 UTC, merged

2023-08-24 15:45 UTC, nojnhuh commented
> I think you also need to update azure-service-operator/v2/config/manager/manager_image_patch.yaml to make the `SUBSCRIPTION_ID` optional.
> 
> Same for `AZURE_TENANT_ID` and `AZURE_CLIENT_ID` which also aren't marked optional right now.

Sorry to dig up ancient history, but was this change ever made? I found that I still had to do this to avoid having to create the aso-controller-settings Secret, otherwise I see an Event prevent ASO from starting:
```
89s         Warning   Failed                  pod/azureserviceoperator-controller-manager-84446f4877-z8jw7    Error: secret "aso-controller-settings" not found
```

https://github.com/Azure/azure-service-operator/blob/239eea73cdc26007005e35d05fe2442ec0e3214a/v2/config/manager/manager_image_patch.yaml#L27-L37

2023-09-05 20:32 UTC, matthchr commented
There was a reason we didnt' do this but I need to dig into why. It may be that it doesn't matter anymore... (IIRC it had to do with pod boot ordering and Helm)