increase test coverage for type_name_set.go
Azure/azure-service-operator pull request #2965
Opened 2023-05-12 06:01 UTC by khareyash05

**What this PR does / why we need it**:

The current test coverage for `type_name_set.go` is  77%. [https://app.codecov.io/gh/Azure/azure-service-operator/blob/master/v2/tools/generator/internal/astmodel/type_name_set.go](https://app.codecov.io/gh/Azure/azure-service-operator/blob/master/v2/tools/generator/internal/astmodel/type_name_set.go). I worked on increasing the test coverage by adding more test cases for `Remove()` and `Equals()`

**If applicable**:
- [ ] this PR contains documentation
- [X] this PR contains tests

2023-05-14 20:11 UTC, theunrepentantgeek requested changes
The new test cases look good. 

Tests is this file are in groups (see the existing code comments on lines #20 and #31) so we need to move things around a little. I've added comments on what's needed, and we can merge this once that's done.

Just FYI - our CI is a little flaky at the moment, so you may see us triggering the CI process multiple times. We're working on tracking down the cause.

2023-05-14 20:11 UTC, theunrepentantgeek commented on v2/tools/generator/internal/astmodel/type_name_set_test.go
> + func Test_TypeNameSet_AfterRemovingOnlyItem_SetIsEmpty(t *testing.T) {
Add new heading for `Remove() tests`

2023-05-14 20:11 UTC, theunrepentantgeek commented on v2/tools/generator/internal/astmodel/type_name_set_test.go
> + func Test_TypeNameSet_Equals_ReturnsTrueForEqualSets(t *testing.T) {
Add new heading for `Equals() Tests`

2023-05-14 20:11 UTC, theunrepentantgeek commented on v2/tools/generator/internal/astmodel/type_name_set_test.go
> +	set1 := NewTypeNameSet(oneTypeName, twoTypeName)
Add a comment highlighting that the two sets are constructed in different orders.

2023-05-14 20:11 UTC, theunrepentantgeek commented on v2/tools/generator/internal/astmodel/type_name_set_test.go
> +}
Move into the section for `Empty Set Tests`

2023-05-14 20:11 UTC, theunrepentantgeek commented on v2/tools/generator/internal/astmodel/type_name_set_test.go
> +}
Move this and the next test into the section for `Remove() Tests`

2023-05-14 20:11 UTC, theunrepentantgeek commented on v2/tools/generator/internal/astmodel/type_name_set_test.go
> +}
Move into the section for `Empty Set Tests`

2023-05-14 23:45 UTC, theunrepentantgeek commented
CI failed with the following error:
```
[generator:lint] internal/astmodel/type_name_set_test.go:51: File is not `gofmt`-ed with `-s` (gofmt)
```

I recommend you run our quick checks locally after making changes to catch these kinds of issue. You just needs to run `task` at the root of the repo; see [Contributing ](https://azure.github.io/azure-service-operator/contributing) for more details.

2023-05-15 20:39 UTC, theunrepentantgeek commented
/ok-to-test sha=168b430

2023-05-16 01:29 UTC, theunrepentantgeek commented
CI failed with the following error:

```
[generator:lint] level=info msg="[runner] linters took 12.533784769s with stages: goanalysis_metalinter: 12.530605737s"
[generator:lint] internal/astmodel/type_name_set_test.go:30:1: Function Test_TypeNameSet_RemoveFromEmptySet_SetUnchanged missing the call to method parallel (paralleltest)
[generator:lint] func Test_TypeNameSet_RemoveFromEmptySet_SetUnchanged(t *testing.T) {
[generator:lint] ^
```

Please fix. Recommend running `task generator:lint` locally to catch these before pushing.

I'm looking forward to merging this, really appreciate your efforts.

2023-05-16 03:05 UTC, khareyash05 commented
@theunrepentantgeek Hi. I am running `task generator:lint` to check if the files are ok to test or not on Github CodeSpaces and I getting this error `task: Command "/workspaces/azure-service-operator/scripts/v2/build_version.py v2" failed: exit status 1`  but when i run `task default` I am getting the list of commands available. I am not able to understand this since its on codespaces and `task default`  is running as well but not `task` or `task generator:lint`

2023-05-16 03:14 UTC, khareyash05 commented
> 

added the paralleltest

2023-05-16 03:15 UTC, khareyash05 commented
> CI failed with the following error:
> 
> ```
> [generator:lint] level=info msg="[runner] linters took 12.533784769s with stages: goanalysis_metalinter: 12.530605737s"
> [generator:lint] internal/astmodel/type_name_set_test.go:30:1: Function Test_TypeNameSet_RemoveFromEmptySet_SetUnchanged missing the call to method parallel (paralleltest)
> [generator:lint] func Test_TypeNameSet_RemoveFromEmptySet_SetUnchanged(t *testing.T) {
> [generator:lint] ^
> ```
> 
> Please fix. Recommend running `task generator:lint` locally to catch these before pushing.
> 
> I'm looking forward to merging this, really appreciate your efforts.

Thank you and added the paralleltest

2023-05-16 04:23 UTC, theunrepentantgeek commented
/ok-to-test sha=0da572b

2023-05-17 20:04 UTC, theunrepentantgeek commented
/ok-to-test sha=180fd52

2023-05-18 01:32 UTC, theunrepentantgeek commented
/azp run

2023-05-18 01:34 UTC, theunrepentantgeek approved these changes

2023-05-18 01:35 UTC, theunrepentantgeek commented
/ok-to-test sha=c437288

2023-05-18 01:35 UTC, theunrepentantgeek commented
/azp run

2023-05-18 02:58 UTC, merged

2023-05-18 02:58 UTC, theunrepentantgeek commented
Merged! Thanks for the contribution @khareyash05