Export API keys for search service
Azure/azure-service-operator pull request #3065
Opened 2023-06-12 00:18 UTC by super-harsh

**What this PR does / why we need it**:

As mentioned in #3053, Adding the support for exporting API keys for Azure Cognitive Search

**Special notes for your reviewer**:

Also had to add the custom key matcher logic to replace/hide the base64 keys without '=' padding for the returned API keys

**If applicable**:
- [x] this PR contains tests

2023-06-12 01:09 UTC, theunrepentantgeek requested changes
Changes look good for exposing the keys, but how are you addressing the ARM API shape required for `apiKeyOnly` access?

The required ARM payload is this:

``` yaml
"authOptions": {
    "apiKeyOnly": {}
}
```

I don't see any changes to the ARM types or the CRD shape in this PR to address this.

2023-06-12 01:09 UTC, theunrepentantgeek commented on v2/api/search/customizations/search_service_extension.go
> +		}
Blank line after closing `}` #nit

2023-06-14 00:37 UTC, theunrepentantgeek approved these changes
Looks good.

2023-06-15 22:03 UTC, matthchr approved these changes

2023-06-15 22:03 UTC, matthchr commented on v2/samples/search/v1api/v1api20220901_searchservice.yaml
> +        name: searchservicekeyssecret
minor: should have a newline at the end here

2023-06-16 01:00 UTC, merged