[Automated] Add API Docs
Azure/azure-service-operator pull request #3084
Opened 2023-06-18 18:33 UTC by theunrepentantgeek

Update API documentation for ASO Custom Resource Definitions

Auto-generated by [create-pull-request][1]

[1]: https://github.com/peter-evans/create-pull-request

2023-06-18 21:41 UTC, super-harsh approved these changes

2023-06-18 21:43 UTC, super-harsh requested changes
These changes are not published yet in the new release. Should the docs still be published?

2023-06-20 01:40 UTC, theunrepentantgeek commented
> These changes are not published yet in the new release. Should the docs still be published?

For now, yes. We haven't decided what change we want to make to handle the versioning issue, so for now I think we continue as we are.

2023-06-20 21:18 UTC, super-harsh approved these changes

2023-06-20 22:09 UTC, merged